# Generated by Django 4.0.3 on 2023-11-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0002_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='status',
            field=models.CharField(choices=[('checkin', 'checkin'), ('checkout', 'checkout')], default='checkin', max_length=20),
        ),
    ]
