# Generated by Django 4.0.3 on 2023-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0003_visitors_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='date_checkout',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
