# Generated by Django 4.2.8 on 2023-12-06 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0006_alter_departments_options_alter_visitors_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='vmsApp.departments'),
        ),
    ]
