# Generated by Django 4.2 on 2024-09-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0007_alter_visitors_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date_checkout',
            field=models.DateTimeField(auto_now_add=True, verbose_name='checkout date'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='checkin date'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='vmsApp.departments', verbose_name='Category'),
        ),
    ]
