# Generated by Django 4.2 on 2024-09-05 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vmsApp', '0008_alter_visitors_date_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
